### PR TITLE
Proper Laravel v6.0 support

### PR DESCRIPTION
**Pull request by sander3**
Hi there 👋

Thank you so much for your great Laravel package! I've just noticed a minor issue in terms of Laravel v6.x support. We switched to semantic versioning with v6 so the range constraints are a bit different.

This pull request aims to resolve that issue.

Have a nice day!

### CODE REVIEW

**Comment by mazedlx** [comment]
Thanks!

**Comment by sander3** [comment]
@mazedlx Could you please tag a release so Composer allows me to upgrade? 😊

```
Package operations: 0 installs, 2 updates, 0 removals
  - Updating laravel/framework (v6.0.4 => v6.7.0): Downloading (100%)         
  - Removing mazedlx/laravel-feature-policy (1.0.9)
  - Installing mazedlx/laravel-feature-policy (dev-master 154885f): Downloading (100%)         
Writing lock file
```

Thanks!

**Comment by mazedlx** [comment]
Done

**Comment by sander3** [comment]
Thank you so much. Have a nice weekend!

**Pull request merged**
